# fly.toml file generated for pauls-plastics on 2023-03-27T11:01:14-04:00

app = "pauls-plastics"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "iad"
processes = []

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
